version: '3.5'

services:
    graphql_django_api-uwsgi:
        image: 057133510824.dkr.ecr.eu-west-3.amazonaws.com/graphql_django_api:latest
        command: ./deploy/prod/uwsgi
        restart: always
        volumes:
            - type: bind
              source: /var/run/graphql_django_api/
              target: /var/run/graphql_django_api/
            - type: bind
              source: /var/dev_data/graphql_django_api/log/
              target: /var/log/graphql_django_api/
            - type: bind
              source: /var/dev_data/graphql_django_api/
              target: /var/dev_data/graphql_django_api/
            - type: volume
              source: datastatic
              target: /opt/graphql_django_api/static_files
        deploy:
          resources:
            limits:
              memory: 200M

volumes:
    datastatic:
        name: graphql_django_api_static